### ISSUE TITLE
첫번째 이슈

### ISSUE THREAD

**Issue by lastmonth00** [lastmonth00/study#1]
Github 사용법 테스트 중입니다.

ded2c42

**Comment by lastmonth00** [comment]
이슈가 해결됨.

**Comment by imdhson** [comment]
sex https://github.com/imdhson/oss_study/invitations

**Comment by imdhson** [comment]
https://github.com/imdhson/oss_study/invitationshttps://github.com/imdhson/oss_study/invitationshttps://github.com/imdhson/oss_study/invitations

**Comment by imdhson** [comment]
sex ha go ship eo yo?
